General:
  CheckpointPath:
    Value:
      Piano: ./checkpoints/music/music_piano
      Pop: ./checkpoints/music/music_pop
  Dataset:
    Settings:
      FeatureSavePath:
        Value: +
      FeatureType:
        Value: CFP
      SavePath:
        Value: ./
  Feature:
    Settings:
      BinsPerOctave:
        Value: 48
      FrequencyCenter:
        Value: 27.5
      FrequencyResolution:
        Value: 2.0
      Gamma:
        Value:
        - 0.24
        - 0.6
        - 1.0
      Harmonic:
        Value: false
      HarmonicNumber:
        Value: 6
      HopSize:
        Value: 0.02
      SamplingRate:
        Value: 44100
      TimeCenter:
        Value: 0.00022287
      WindowSize:
        Value: 7939
  Inference:
    Settings:
      DuraTh:
        Value: 0.5
      FrameTh:
        Value: 0.5
      InstTh:
        Value: 1.1
      MinLength:
        Value: 0.05
      OnsetTh:
        Value: 6.0
  Model:
    Settings:
      ModelType:
        Value: attn
      SavePath:
        Value: ./checkpoints/music
      SavePrefix:
        Value: music
  Training:
    Settings:
      BatchSize:
        Value: 8
      Channels:
        Value:
        - Spec
        - Ceps
      EarlyStop:
        Value: 6
      Epoch:
        Value: 20
      LabelType:
        Value: note-stream
      LossFunction:
        Value: smooth
      Steps:
        Value: 3000
      Timesteps:
        Value: 128
      ValBatchSize:
        Value: 8
      ValSteps:
        Value: 500
      FeatureNum:
        Value: 352
  TranscriptionMode:
    Value: Stream
