name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Publish to pypi
        run: |
          python -m pip install --upgrade pip setuptools
          pip install poetry
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: mctlab
          password: ${{ secrets.DOCKER_HUB_PASSWD }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Publish docker image
        env:
          TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker build -t omnizart:${TAG} .
          docker tag omnizart:${TAG} mctlab/omnizart:${TAG}
          docker tag omnizart:${TAG} mctlab/omnizart:latest
          docker push mctlab/omnizart
      - name: Create release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          prerelease: false
          draft: false
